# Generated by Django 5.0.6 on 2024-05-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_question_correct_answer_delete_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')]),
        ),
    ]
