# Generated by Django 5.0.6 on 2024-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_equationquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField()),
                ('constant', models.IntegerField()),
                ('solution', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EquationQuestion',
        ),
    ]
