# Generated by Django 5.0.6 on 2024-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_equation_delete_equationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation',
            name='correct_answer',
            field=models.FloatField(default=0),
        ),
    ]
