# Generated by Django 5.0.6 on 2024-06-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_category_problem_quiz_subcategory_delete_equation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='question_text_template',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
