# Generated by Django 5.0.6 on 2024-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_rename_question_text_template_problem_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='math_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='question_text',
            field=models.CharField(max_length=250),
        ),
    ]
