# Generated by Django 5.0.6 on 2024-06-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_problem_math_text_alter_problem_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='math_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
