# Generated by Django 5.0.6 on 2024-06-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_fill_math_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='math_text',
            field=models.CharField(default=''),
        ),
    ]
