# Generated by Django 5.0.6 on 2024-06-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_alter_problem_math_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='math_text',
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_formula',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question_text',
            field=models.CharField(default=''),
        ),
    ]
