# Generated by Django 5.0.6 on 2024-06-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_remove_problem_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct_option',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
    ]
