# Generated by Django 5.0.6 on 2024-06-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_studentprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogress',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='studentprogress',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='studentprogress',
            old_name='user_id',
            new_name='user',
        ),
    ]
